/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Producto;

import Controladores.AudifonosJpaController;
import Controladores.CableJpaController;
import Controladores.CamaraJpaController;
import Controladores.CargadorJpaController;
import Controladores.ControladorvozJpaController;
import Controladores.InterruptorJpaController;
import Controladores.LlaveautomaticaJpaController;
import Controladores.RelojJpaController;
import Controladores.SensorJpaController;
import Controladores.TomacorrienteJpaController;
import Controladores.exceptions.NonexistentEntityException;
import Entidades.Audifonos;
import Entidades.Cable;
import Entidades.Camara;
import Entidades.Cargador;
import Entidades.Controladorvoz;
import Entidades.Interruptor;
import Entidades.Llaveautomatica;
import Entidades.Reloj;
import Entidades.Sensor;
import Entidades.Tomacorriente;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class ProductoEliminar extends javax.swing.JInternalFrame {

    /**
     * Creates new form ProductoActualizar
     */
    CableJpaController Cca = new CableJpaController();
    Cable ca = new Cable();
    AudifonosJpaController Cau = new AudifonosJpaController();
    Audifonos au = new Audifonos();
    CamaraJpaController Ccam = new CamaraJpaController();
    Camara cam = new Camara();
    CargadorJpaController Ccar = new CargadorJpaController();
    Cargador car = new Cargador();
    InterruptorJpaController Cin = new InterruptorJpaController();
    Interruptor in = new Interruptor();
    TomacorrienteJpaController Cto = new TomacorrienteJpaController();
    Tomacorriente toma = new Tomacorriente();
    SensorJpaController Cse = new SensorJpaController();
    Sensor se = new Sensor();
    ControladorvozJpaController Ccv = new ControladorvozJpaController();
    Controladorvoz cv = new Controladorvoz();
    LlaveautomaticaJpaController Clla = new LlaveautomaticaJpaController();
    Llaveautomatica lla = new Llaveautomatica();
    RelojJpaController Creloj = new RelojJpaController();
    Reloj r = new Reloj();
    String CodigoProducto = "";

    public ProductoEliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonRegresar = new javax.swing.JButton();
        jBotonEliminar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        cbxProductoEliminar = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableProductoEliminar = new javax.swing.JTable();

        jLabel1.setText("Seleccione producto a actualizar:");

        jButtonRegresar.setText("Regresar");
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jBotonEliminar.setText("Eliminar");
        jBotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonEliminarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("ELIMINACIÓN DE PRODUCTO");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabelLogo.setBackground(new java.awt.Color(204, 204, 204));
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/GZlogohor3-01_200x.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabelLogo)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        cbxProductoEliminar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione un producto a eliminar", "RJ-Reloj", "AU-Audifonos", "CM-Cámara", "CA-Cargador", "CB-Cable", "IN-Interruptor", "TO-Tomacorriente", "SE-Sensor", "CZ-ControladorVoz", "La-Llaves Automáticas" }));
        cbxProductoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProductoEliminarActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jTableProductoEliminar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Modelo ", "Marca", "Longitud", "Resolución", "Tipo", "Angulo de Abertura", "Whatts", "Tamaño", "NumeroBotones", "Gama", "Sumergible", "SistemaAndroid", "Forma", "Precio Importación", "Precio Público", "Cantidad", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProductoEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductoEliminarMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableProductoEliminar);
        if (jTableProductoEliminar.getColumnModel().getColumnCount() > 0) {
            jTableProductoEliminar.getColumnModel().getColumn(0).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(1).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(2).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(3).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(4).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(5).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(6).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(7).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(8).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(9).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(10).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(11).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(12).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(13).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(14).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(15).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(16).setResizable(false);
            jTableProductoEliminar.getColumnModel().getColumn(17).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotonEliminar)
                .addGap(66, 66, 66)
                .addComponent(jButtonRegresar)
                .addGap(261, 261, 261))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbxProductoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButtonBuscar)
                .addContainerGap(740, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxProductoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonEliminar)
                    .addComponent(jButtonRegresar))
                .addGap(361, 361, 361))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonRegresarActionPerformed

    private void jBotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonEliminarActionPerformed
        try {
            
           
            if (this.cbxProductoEliminar.getSelectedItem().equals("Selecione un producto a eliminar")) {
               JOptionPane.showMessageDialog(null, "Selecione un producto", "CAMPO No selecionado", JOptionPane.WARNING_MESSAGE);

            } else if(CodigoProducto.equals("")){
                  JOptionPane.showMessageDialog(null, "Selecione un producto de la tabla");
            }else if (this.cbxProductoEliminar.getSelectedItem().equals("CB-Cable")) {
                Cca.destroy(CodigoProducto);
                JOptionPane.showMessageDialog(null, "Producto Eliminado");
                CargarTabla();
            } else if (this.cbxProductoEliminar.getSelectedItem().equals("AU-Audifonos")) {
                Cau.destroy(CodigoProducto);
                JOptionPane.showMessageDialog(null, "Producto Eliminado");
                CargarTabla();
            } else if (this.cbxProductoEliminar.getSelectedItem().equals("CM-Cámara")) {
                Ccam.destroy(CodigoProducto);
                JOptionPane.showMessageDialog(null, "Producto Eliminado");
                CargarTabla();
            } else if (this.cbxProductoEliminar.getSelectedItem().equals("RJ-Reloj")) {
                Creloj.destroy(CodigoProducto);
                JOptionPane.showMessageDialog(null, "Producto Eliminado");
                CargarTabla();
            } else if (this.cbxProductoEliminar.getSelectedItem().equals("CA-Cargador")) {
                Ccar.destroy(CodigoProducto);
                JOptionPane.showMessageDialog(null, "Producto Eliminado");
                CargarTabla();
            } else if (this.cbxProductoEliminar.getSelectedItem().equals("IN-Interruptor")) {
                Cin.destroy(CodigoProducto);
                JOptionPane.showMessageDialog(null, "Producto Eliminado");
                CargarTabla();
            } else if (this.cbxProductoEliminar.getSelectedItem().equals("TO-Tomacorriente")) {
                Cto.destroy(CodigoProducto);
                JOptionPane.showMessageDialog(null, "Producto Eliminado");
                CargarTabla();
            } else if (this.cbxProductoEliminar.getSelectedItem().equals("SE-Sensor")) {
                Cse.destroy(CodigoProducto);
                JOptionPane.showMessageDialog(null, "Producto Eliminado");
                CargarTabla();
            } else if (this.cbxProductoEliminar.getSelectedItem().equals("CZ-ControladorVoz")) {
                Ccv.destroy(CodigoProducto);
                JOptionPane.showMessageDialog(null, "Producto Eliminado");
                CargarTabla();
            } else if (this.cbxProductoEliminar.getSelectedItem().equals("La-Llaves Automáticas")) {
                Clla.destroy(CodigoProducto);
                JOptionPane.showMessageDialog(null, "Producto Eliminado");
                CargarTabla();
            }

        } catch (NonexistentEntityException ex) {
            Logger.getLogger(ProductoEliminar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBotonEliminarActionPerformed

    private void cbxProductoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductoEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProductoEliminarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        CargarTabla();

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jTableProductoEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductoEliminarMouseClicked
        // TODO add your handling code here:
         CodigoProducto = (String) jTableProductoEliminar.getValueAt(jTableProductoEliminar.getSelectedRow(), 0);
    }//GEN-LAST:event_jTableProductoEliminarMouseClicked
    public void CargarTabla() {

        if (this.cbxProductoEliminar.getSelectedItem().equals("Selecione un producto a eliminar")) {
            JOptionPane.showMessageDialog(null, "Selecione un producto", "CAMPO No selecionado", JOptionPane.WARNING_MESSAGE);
        } else if (this.cbxProductoEliminar.getSelectedItem().equals("CB-Cable")) {
            //Sección 1 
            List<Cable> listC = Cca.findCableEntities();
            DefaultTableModel modelo = (DefaultTableModel) jTableProductoEliminar.getModel();
            modelo.setRowCount(0);
            //Sección 2
            Object[] Columna = new Object[18];
            //Sección 3
            for (int i = 0; i < listC.size(); i++) {
                Columna[0] = listC.get(i).getCodigo();
                Columna[1] = listC.get(i).getModelo();
                Columna[2] = listC.get(i).getMarca();
                Columna[3] = listC.get(i).getLongitud();
                Columna[14] = listC.get(i).getPrecioimportacion();
                Columna[15] = listC.get(i).getPreciopublico();
                Columna[16] = listC.get(i).getCantidad();
                Columna[17] = listC.get(i).getEstado();
                modelo.addRow(Columna);
            }
            jTableProductoEliminar.setModel(modelo);
            if (listC.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No existe Producto", "No se encuentra", JOptionPane.WARNING_MESSAGE);
            }
        } else if (this.cbxProductoEliminar.getSelectedItem().equals("AU-Audifonos")) {

            //Sección 1 
            List<Audifonos> listAu = Cau.findAudifonosEntities();
            DefaultTableModel modelo = (DefaultTableModel) jTableProductoEliminar.getModel();
            modelo.setRowCount(0);
            //Sección 2
            Object[] Columna = new Object[18];
            //Sección 3
            for (int i = 0; i < listAu.size(); i++) {
                Columna[0] = listAu.get(i).getCodigo();
                Columna[1] = listAu.get(i).getModelo();
                Columna[2] = listAu.get(i).getMarca();
                Columna[5] = listAu.get(i).getTipo();
                Columna[14] = listAu.get(i).getPrecioimportacion();
                Columna[15] = listAu.get(i).getPreciopublico();
                Columna[16] = listAu.get(i).getCantidad();
                Columna[17] = listAu.get(i).getEstado();
                modelo.addRow(Columna);
            }
            jTableProductoEliminar.setModel(modelo);
            if (listAu.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No existe Producto", "No se encuentra", JOptionPane.WARNING_MESSAGE);
            }
        } else if (this.cbxProductoEliminar.getSelectedItem().equals("CM-Cámara")) {
            //Sección 1 
            List<Camara> listcam = Ccam.findCamaraEntities();
            DefaultTableModel modelo = (DefaultTableModel) jTableProductoEliminar.getModel();
            modelo.setRowCount(0);
            //Sección 2
            Object[] Columna = new Object[18];
            //Sección 3
            for (int i = 0; i < listcam.size(); i++) {
                Columna[0] = listcam.get(i).getCodigo();
                Columna[1] = listcam.get(i).getModelo();
                Columna[2] = listcam.get(i).getMarca();
                Columna[4] = listcam.get(i).getResolucion();
                Columna[5] = listcam.get(i).getTipo();
                Columna[6] = listcam.get(i).getAnguloavertura();
                Columna[14] = listcam.get(i).getPrecioimportacion();
                Columna[15] = listcam.get(i).getPreciopublico();
                Columna[16] = listcam.get(i).getCantidad();
                Columna[17] = listcam.get(i).getEstado();
                modelo.addRow(Columna);
            }
            jTableProductoEliminar.setModel(modelo);
            if (listcam.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No existe Producto", "No se encuentra", JOptionPane.WARNING_MESSAGE);
            }

        } else if (this.cbxProductoEliminar.getSelectedItem().equals("CA-Cargador")) {
            List<Cargador> listcar = Ccar.findCargadorEntities();
            DefaultTableModel modelo = (DefaultTableModel) jTableProductoEliminar.getModel();
            modelo.setRowCount(0);
            //Sección 2
            Object[] Columna = new Object[18];
            //Sección 3
            for (int i = 0; i < listcar.size(); i++) {
                Columna[0] = listcar.get(i).getCodigo();
                Columna[1] = listcar.get(i).getModelo();
                Columna[2] = listcar.get(i).getMarca();
                Columna[5] = listcar.get(i).getTipo();
                Columna[7] = listcar.get(i).getWattscarga();
                Columna[14] = listcar.get(i).getPrecioimportacion();
                Columna[15] = listcar.get(i).getPreciopublico();
                Columna[16] = listcar.get(i).getCantidad();
                Columna[17] = listcar.get(i).getEstado();
                modelo.addRow(Columna);
            }
            jTableProductoEliminar.setModel(modelo);
            if (listcar.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No existe Producto", "No se encuentra", JOptionPane.WARNING_MESSAGE);
            }

        } else if (this.cbxProductoEliminar.getSelectedItem().equals("IN-Interruptor")) {
            List<Interruptor> listint = Cin.findInterruptorEntities();
            DefaultTableModel modelo = (DefaultTableModel) jTableProductoEliminar.getModel();
            modelo.setRowCount(0);
            //Sección 2
            Object[] Columna = new Object[18];
            //Sección 3
            for (int i = 0; i < listint.size(); i++) {
                Columna[0] = listint.get(i).getCodigo();
                Columna[1] = listint.get(i).getModelo();
                Columna[2] = listint.get(i).getMarca();
                Columna[9] = listint.get(i).getNumerobotones();
                Columna[5] = listint.get(i).getTipo();
                Columna[14] = listint.get(i).getPrecioimportacion();
                Columna[15] = listint.get(i).getPreciopublico();
                Columna[16] = listint.get(i).getCantidad();
                Columna[17] = listint.get(i).getEstado();
                modelo.addRow(Columna);
            }
            jTableProductoEliminar.setModel(modelo);
            if (listint.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No existe Producto", "No se encuentra", JOptionPane.WARNING_MESSAGE);
            }

        } else if (this.cbxProductoEliminar.getSelectedItem().equals("TO-Tomacorriente")) {
            List<Tomacorriente> listtom = Cto.findTomacorrienteEntities();
            DefaultTableModel modelo = (DefaultTableModel) jTableProductoEliminar.getModel();
            modelo.setRowCount(0);
            //Sección 2
            Object[] Columna = new Object[18];
            //Sección 3
            for (int i = 0; i < listtom.size(); i++) {
                Columna[0] = listtom.get(i).getCodigo();
                Columna[1] = listtom.get(i).getModelo();
                Columna[2] = listtom.get(i).getMarca();
                Columna[5] = listtom.get(i).getTipo();
                Columna[13] = listtom.get(i).getForma();
                Columna[14] = listtom.get(i).getPrecioimportacion();
                Columna[15] = listtom.get(i).getPreciopublico();
                Columna[16] = listtom.get(i).getCantidad();
                Columna[17] = listtom.get(i).getEstado();
                modelo.addRow(Columna);
            }
            jTableProductoEliminar.setModel(modelo);
            if (listtom.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No existe Producto", "No se encuentra", JOptionPane.WARNING_MESSAGE);
            }
        } else if (this.cbxProductoEliminar.getSelectedItem().equals("SE-Sensor")) {
            List<Sensor> listsem = Cse.findSensorEntities();
            DefaultTableModel modelo = (DefaultTableModel) jTableProductoEliminar.getModel();
            modelo.setRowCount(0);
            //Sección 2
            Object[] Columna = new Object[18];
            //Sección 3
            for (int i = 0; i < listsem.size(); i++) {
                Columna[0] = listsem.get(i).getCodigo();
                Columna[1] = listsem.get(i).getModelo();
                Columna[2] = listsem.get(i).getMarca();
                Columna[5] = listsem.get(i).getTipo();
                Columna[14] = listsem.get(i).getPrecioimportacion();
                Columna[15] = listsem.get(i).getPreciopublico();
                Columna[16] = listsem.get(i).getCantidad();
                Columna[17] = listsem.get(i).getEstado();
                modelo.addRow(Columna);
            }
            jTableProductoEliminar.setModel(modelo);
            if (listsem.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No existe Producto", "No se encuentra", JOptionPane.WARNING_MESSAGE);
            }
        } else if (this.cbxProductoEliminar.getSelectedItem().equals("CZ-ControladorVoz")) {
            List<Controladorvoz> listcv = Ccv.findControladorvozEntities();
            DefaultTableModel modelo = (DefaultTableModel) jTableProductoEliminar.getModel();
            modelo.setRowCount(0);
            //Sección 2
            Object[] Columna = new Object[18];
            //Sección 3
            for (int i = 0; i < listcv.size(); i++) {
                Columna[0] = listcv.get(i).getCodigo();
                Columna[1] = listcv.get(i).getModelo();
                Columna[2] = listcv.get(i).getMarca();
                Columna[8] = listcv.get(i).getTamaño();
                Columna[14] = listcv.get(i).getPrecioimportacion();
                Columna[15] = listcv.get(i).getPreciopublico();
                Columna[16] = listcv.get(i).getCantidad();
                Columna[17] = listcv.get(i).getEstado();
                modelo.addRow(Columna);
            }
            jTableProductoEliminar.setModel(modelo);
            if (listcv.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No existe Producto", "No se encuentra", JOptionPane.WARNING_MESSAGE);
            }
        } else if (this.cbxProductoEliminar.getSelectedItem().equals("La-Llaves Automáticas")) {
            List<Llaveautomatica> listlla = Clla.findLlaveautomaticaEntities();
            DefaultTableModel modelo = (DefaultTableModel) jTableProductoEliminar.getModel();
            modelo.setRowCount(0);
            //Sección 2
            Object[] Columna = new Object[18];
            //Sección 3
            for (int i = 0; i < listlla.size(); i++) {
                Columna[0] = listlla.get(i).getCodigo();
                Columna[1] = listlla.get(i).getModelo();
                Columna[2] = listlla.get(i).getMarca();
                Columna[14] = listlla.get(i).getPrecioimportacion();
                Columna[15] = listlla.get(i).getPreciopublico();
                Columna[16] = listlla.get(i).getCantidad();
                Columna[17] = listlla.get(i).getEstado();
                modelo.addRow(Columna);
            }
            jTableProductoEliminar.setModel(modelo);
            if (listlla.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No existe Producto", "No se encuentra", JOptionPane.WARNING_MESSAGE);
            }
        } else if (this.cbxProductoEliminar.getSelectedItem().equals("RJ-Reloj")) {
            List<Reloj> listrej = Creloj.findRelojEntities();
            DefaultTableModel modelo = (DefaultTableModel) jTableProductoEliminar.getModel();
            modelo.setRowCount(0);
            //Sección 2
            Object[] Columna = new Object[18];
            //Sección 3
            for (int i = 0; i < listrej.size(); i++) {
                Columna[0] = listrej.get(i).getCodigo();
                Columna[1] = listrej.get(i).getModelo();
                Columna[2] = listrej.get(i).getMarca();
                Columna[10] = listrej.get(i).getGama();
                Columna[11] = listrej.get(i).getSumergible();
                Columna[12] = listrej.get(i).getSistemaandroid();
                Columna[14] = listrej.get(i).getPrecioimportacion();
                Columna[15] = listrej.get(i).getPreciopublico();
                Columna[16] = listrej.get(i).getCantidad();
                Columna[17] = listrej.get(i).getEstado();
                modelo.addRow(Columna);
            }
            jTableProductoEliminar.setModel(modelo);
            if (listrej.isEmpty()) {
                JOptionPane.showMessageDialog(null, "No existe Producto", "No se encuentra", JOptionPane.WARNING_MESSAGE);
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxProductoEliminar;
    private javax.swing.JButton jBotonEliminar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableProductoEliminar;
    // End of variables declaration//GEN-END:variables
}
