/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inicio;

import Cliente.ConsultaCliente;
import Cliente.ActualizarCliente;
import Cliente.Registro_Cliente;
import Empleado.ActualizarEmpleado;
import Empleado.ConsultarEmpleado;
import Empleado.RegistroEmpleado;
import Inventario.StockActualizar;
import Producto.ProductoConsultar;
import Ventas.AgregarProducto;
import Actualizar_Producto.*;
import Cliente.EliminarCliente;
import Empleado.EliminarEmpleado;
import Inventario.StockConsulta;
import Producto.ProductoEliminar;

import Registro_Producto.Audifonos_R;
import Registro_Producto.Cable_R;
import Registro_Producto.Camara_Seguridad;
import Registro_Producto.Cargador_R;
import Registro_Producto.Controlador_Voz;
import Registro_Producto.Interruptor_R;
import Registro_Producto.Llave_Automatica;
import Registro_Producto.Reloj_R;
import Registro_Producto.Sensor_R;
import Registro_Producto.Tomacorriente_R;
import Ventas.VentaConsulta;
import Ventas.VentaRegistro;
import java.awt.event.ActionEvent;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Menu extends javax.swing.JFrame {

//Inventario
    StockActualizar SA = new StockActualizar();
    StockConsulta SC = new StockConsulta();

//Producto
    ProductoConsultar PC = new ProductoConsultar();
    ProductoEliminar PE = new ProductoEliminar();

//vendedor factura
    VentaRegistro VR1 = new VentaRegistro();
    VentaConsulta VC1 = new VentaConsulta();
    AgregarProducto IC1 = new AgregarProducto();

//clientes
    Registro_Cliente RC1 = new Registro_Cliente();
    ActualizarCliente AC = new ActualizarCliente();
    ConsultaCliente CC = new ConsultaCliente();
    EliminarCliente EC = new EliminarCliente();

//Productos registrar
    Audifonos_R A = new Audifonos_R();
    Cable_R CA = new Cable_R();
    Camara_Seguridad CS = new Camara_Seguridad();
    Cargador_R CG = new Cargador_R();
    Controlador_Voz CV = new Controlador_Voz();
    Interruptor_R I = new Interruptor_R();
    Llave_Automatica LA = new Llave_Automatica();
    Reloj_R R = new Reloj_R();
    Sensor_R S = new Sensor_R();
    Tomacorriente_R TC = new Tomacorriente_R();

//PRODUCTO actualizar
    A_Audifonos AAU = new A_Audifonos();
    A_Cable ACA = new A_Cable();
    A_Camara_Seguridad ACS = new A_Camara_Seguridad();
    A_Cargador ACR = new A_Cargador();
    A_Controlador_Voz ACV = new A_Controlador_Voz();
    A_Interruptor AI = new A_Interruptor();
    A_Llave_Automatica AL = new A_Llave_Automatica();
    A_Reloj AR = new A_Reloj();
    A_Tomacorriente AT = new A_Tomacorriente();
    A_Sensor AS = new A_Sensor();

//EMPLEADO
    ActualizarEmpleado AE = new ActualizarEmpleado();
    ConsultarEmpleado CE = new ConsultarEmpleado();
    RegistroEmpleado RE = new RegistroEmpleado();
    EliminarEmpleado EE = new EliminarEmpleado();

    /**
     * Creates new form Menú
     */
    public Menu() {
        initComponents();
        this.setTitle("SiGIn-GIZPIRIT");
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu4 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        ModuloCliente = new javax.swing.JMenu();
        ClienteRegistrar = new javax.swing.JMenuItem();
        ClienteActualizar = new javax.swing.JMenuItem();
        ClienteConsultar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ClienteEliminar = new javax.swing.JMenuItem();
        ModuloVentas = new javax.swing.JMenu();
        VentaFactura = new javax.swing.JMenuItem();
        VentaConsultar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        ModuloEmpleado = new javax.swing.JMenu();
        EmpleadoRegistrar = new javax.swing.JMenuItem();
        EmpleadoConsultar = new javax.swing.JMenuItem();
        EmpleadoActualizar = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        EmpleadoEliminar = new javax.swing.JMenuItem();
        ModuloProducto = new javax.swing.JMenu();
        ProductoRegistrar = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        ProductoActualizar = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        ProductoEliminar = new javax.swing.JMenuItem();
        ProductoConsultar = new javax.swing.JMenuItem();
        ModuloInventario = new javax.swing.JMenu();
        InvantarioConsultar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        InvantarioActualizar = new javax.swing.JMenuItem();
        InvantarioReporte = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        ModuloAdministracion = new javax.swing.JMenu();
        AdministracionUsuario = new javax.swing.JMenuItem();
        AdministracionParameetros = new javax.swing.JMenuItem();
        AdministracionAuditoria = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("jMenu4");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        escritorio.setBackground(new java.awt.Color(51, 153, 0));
        escritorio.setForeground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
        );

        ModuloCliente.setText("Cliente");
        ModuloCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ClienteRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ClienteRegistrar.setText("Registrar");
        ClienteRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteRegistrarActionPerformed(evt);
            }
        });
        ModuloCliente.add(ClienteRegistrar);

        ClienteActualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ClienteActualizar.setText("Actualizar");
        ClienteActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActualizarActionPerformed(evt);
            }
        });
        ModuloCliente.add(ClienteActualizar);

        ClienteConsultar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ClienteConsultar.setText("Consultar");
        ClienteConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteConsultarActionPerformed(evt);
            }
        });
        ModuloCliente.add(ClienteConsultar);
        ModuloCliente.add(jSeparator1);

        ClienteEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ClienteEliminar.setText("Eliminar");
        ClienteEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteEliminarActionPerformed(evt);
            }
        });
        ModuloCliente.add(ClienteEliminar);

        jMenuBar2.add(ModuloCliente);

        ModuloVentas.setText("Venta");
        ModuloVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        VentaFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VentaFactura.setText("Facturar");
        VentaFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentaFacturaActionPerformed(evt);
            }
        });
        ModuloVentas.add(VentaFactura);

        VentaConsultar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        VentaConsultar.setText("Consultar");
        VentaConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentaConsultarActionPerformed(evt);
            }
        });
        ModuloVentas.add(VentaConsultar);
        ModuloVentas.add(jSeparator2);

        jMenuBar2.add(ModuloVentas);

        ModuloEmpleado.setText("Empleado");
        ModuloEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        EmpleadoRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmpleadoRegistrar.setText("Registrar");
        EmpleadoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadoRegistrarActionPerformed(evt);
            }
        });
        ModuloEmpleado.add(EmpleadoRegistrar);

        EmpleadoConsultar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmpleadoConsultar.setText("Consultar");
        EmpleadoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadoConsultarActionPerformed(evt);
            }
        });
        ModuloEmpleado.add(EmpleadoConsultar);

        EmpleadoActualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmpleadoActualizar.setText("Actualizar");
        EmpleadoActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadoActualizarActionPerformed(evt);
            }
        });
        ModuloEmpleado.add(EmpleadoActualizar);
        ModuloEmpleado.add(jSeparator5);

        EmpleadoEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EmpleadoEliminar.setText("Eliminar");
        EmpleadoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpleadoEliminarActionPerformed(evt);
            }
        });
        ModuloEmpleado.add(EmpleadoEliminar);

        jMenuBar2.add(ModuloEmpleado);

        ModuloProducto.setText("Producto");
        ModuloProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ProductoRegistrar.setText("Registrar");
        ProductoRegistrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu11.setText("Domótica");
        jMenu11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem17.setText("Interruptor");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem17);

        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem18.setText("Tomacorriente");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem18);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Sensor");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem3);

        jMenuItem19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem19.setText("Controlador de Voz");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem19);

        jMenuItem20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem20.setText("Llave automática ");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem20);

        ProductoRegistrar.add(jMenu11);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setText("Reloj");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        ProductoRegistrar.add(jMenuItem4);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setText("Audífono");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        ProductoRegistrar.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setText("Cámara de Seguridad");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        ProductoRegistrar.add(jMenuItem7);

        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem11.setText("Cargador");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        ProductoRegistrar.add(jMenuItem11);

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem14.setText("Cable");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        ProductoRegistrar.add(jMenuItem14);

        ModuloProducto.add(ProductoRegistrar);

        ProductoActualizar.setText("Actualizar");
        ProductoActualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenu15.setText("Domotica");

        jMenuItem36.setText("Tomacorriente");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem36);

        jMenuItem35.setText("Interruptor");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem35);

        jMenuItem34.setText("Sensor");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem34);

        jMenuItem33.setText("Controlador de voz");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem33);

        jMenuItem37.setText("Llave automática");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem37);

        ProductoActualizar.add(jMenu15);

        jMenuItem28.setText("Audífonos");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        ProductoActualizar.add(jMenuItem28);

        jMenuItem29.setText("Reloj");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        ProductoActualizar.add(jMenuItem29);

        jMenuItem31.setText("Cable");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        ProductoActualizar.add(jMenuItem31);

        jMenuItem32.setText("Cámara de Seguridad");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        ProductoActualizar.add(jMenuItem32);

        jMenuItem30.setText("Cargador");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        ProductoActualizar.add(jMenuItem30);

        ModuloProducto.add(ProductoActualizar);

        ProductoEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProductoEliminar.setText("Eliminar");
        ProductoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoEliminarActionPerformed(evt);
            }
        });
        ModuloProducto.add(ProductoEliminar);

        ProductoConsultar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProductoConsultar.setText("Consultar");
        ProductoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoConsultarActionPerformed(evt);
            }
        });
        ModuloProducto.add(ProductoConsultar);

        jMenuBar2.add(ModuloProducto);

        ModuloInventario.setText("Inventario");
        ModuloInventario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        InvantarioConsultar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InvantarioConsultar.setText("Consultar Stock");
        InvantarioConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvantarioConsultarActionPerformed(evt);
            }
        });
        ModuloInventario.add(InvantarioConsultar);
        ModuloInventario.add(jSeparator4);

        InvantarioActualizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InvantarioActualizar.setText("Actualizar Stock");
        InvantarioActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvantarioActualizarActionPerformed(evt);
            }
        });
        ModuloInventario.add(InvantarioActualizar);

        InvantarioReporte.setText("Reporte Producto");
        InvantarioReporte.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem23.setText("Reporte por Alta");
        InvantarioReporte.add(jMenuItem23);

        jMenuItem24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem24.setText("Reporte por Baja");
        InvantarioReporte.add(jMenuItem24);

        jMenuItem26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem26.setText("Reporte por Alto Stock");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        InvantarioReporte.add(jMenuItem26);

        jMenuItem27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem27.setText("Reporte por Bajo Stock");
        InvantarioReporte.add(jMenuItem27);

        ModuloInventario.add(InvantarioReporte);

        jMenuBar2.add(ModuloInventario);

        ModuloAdministracion.setText("Administración del Sistema ");
        ModuloAdministracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        AdministracionUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AdministracionUsuario.setText("Administración de Usuario");
        AdministracionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministracionUsuarioActionPerformed(evt);
            }
        });
        ModuloAdministracion.add(AdministracionUsuario);

        AdministracionParameetros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AdministracionParameetros.setText("Administración de Parámetros");
        ModuloAdministracion.add(AdministracionParameetros);

        AdministracionAuditoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AdministracionAuditoria.setText("Auditoría");
        AdministracionAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministracionAuditoriaActionPerformed(evt);
            }
        });
        ModuloAdministracion.add(AdministracionAuditoria);

        jMenuBar2.add(ModuloAdministracion);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void ClienteActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActualizarActionPerformed
        escritorio.add(AC);
        AC.show();
        try {
            AC.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ClienteActualizarActionPerformed

    private void ClienteConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteConsultarActionPerformed
        escritorio.add(CC);
        CC.show();
        try {
            CC.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_ClienteConsultarActionPerformed

    private void EmpleadoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoRegistrarActionPerformed

        escritorio.add(RE);
        RE.show();
        try {
            RE.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_EmpleadoRegistrarActionPerformed

    private void EmpleadoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoConsultarActionPerformed

        escritorio.add(CE);
        CE.show();
        try {
            CE.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_EmpleadoConsultarActionPerformed

    private void InvantarioConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvantarioConsultarActionPerformed

        escritorio.add(SC);
        SC.show();
        try {
            SC.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_InvantarioConsultarActionPerformed

    private void VentaFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentaFacturaActionPerformed

        escritorio.add(VR1);
        VR1.show();
        try {
            VR1.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_VentaFacturaActionPerformed

    private void VentaConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentaConsultarActionPerformed

        escritorio.add(VC1);
        VC1.show();
        try {
            VC1.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_VentaConsultarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

        if (JOptionPane.showConfirmDialog(null, "¿Está seguro?") == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void EmpleadoActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoActualizarActionPerformed

        escritorio.add(AE);
        AE.show();
        try {
            AE.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_EmpleadoActualizarActionPerformed

    private void ClienteRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteRegistrarActionPerformed
        // TODO add your handling code here:
        escritorio.add(RC1);
        RC1.show();
        try {
            RC1.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ClienteRegistrarActionPerformed

    private void AdministracionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministracionUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdministracionUsuarioActionPerformed

    private void AdministracionAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministracionAuditoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdministracionAuditoriaActionPerformed

    private void InvantarioActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvantarioActualizarActionPerformed
        escritorio.add(SA);
        SA.show();
        try {
            SA.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_InvantarioActualizarActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        escritorio.add(CA);
        CA.show();
        try {
            CA.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        escritorio.add(CG);
        CG.show();
        try {
            CG.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        escritorio.add(CS);
        CS.show();
        try {
            CS.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        escritorio.add(A);
        A.show();
        try {
            A.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        escritorio.add(R);
        R.show();
        try {
            R.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        escritorio.add(LA);
        LA.show();
        try {
            LA.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        escritorio.add(CV);
        CV.show();
        try {
            CV.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        escritorio.add(S);
        S.show();
        try {
            S.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        escritorio.add(TC);
        TC.show();
        try {
            TC.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        escritorio.add(I);
        I.show();
        try {
            I.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        // TODO add your handling code here:
        escritorio.add(AAU);
        AAU.show();
        try {
            AAU.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        // TODO add your handling code here:
        escritorio.add(AT);
        AT.show();
        try {
            AT.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        // TODO add your handling code here:
        escritorio.add(AI);
        AI.show();
        try {
            AI.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        // TODO add your handling code here:
        escritorio.add(AS);
        AS.show();
        try {
            AS.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        // TODO add your handling code here:
        escritorio.add(ACV);
        ACV.show();
        try {
            ACV.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        // TODO add your handling code here:
        escritorio.add(AL);
        AL.show();
        try {
            AL.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        // TODO add your handling code here:
        escritorio.add(AR);
        AR.show();
        try {
            AR.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        // TODO add your handling code here:
        escritorio.add(ACA);
        ACA.show();
        try {
            ACA.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        // TODO add your handling code here:
        escritorio.add(ACS);
        ACS.show();
        try {
            ACS.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        // TODO add your handling code here:
        escritorio.add(ACR);
        ACR.show();
        try {
            ACR.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void ProductoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoEliminarActionPerformed
        // TODO add your handling code here:
        escritorio.add(PE);
        PE.show();
        try {
            PE.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ProductoEliminarActionPerformed

    private void ClienteEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteEliminarActionPerformed

        escritorio.add(EC);
        EC.show();
        try {
            EC.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_ClienteEliminarActionPerformed

    private void EmpleadoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpleadoEliminarActionPerformed
        escritorio.add(EE);
        EE.show();
        try {
            EE.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EmpleadoEliminarActionPerformed

    private void ProductoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoConsultarActionPerformed
        // TODO add your handling code here:
        escritorio.add(PC);
        PC.show();
        try {
            PC.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ProductoConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AdministracionAuditoria;
    private javax.swing.JMenuItem AdministracionParameetros;
    private javax.swing.JMenuItem AdministracionUsuario;
    private javax.swing.JMenuItem ClienteActualizar;
    private javax.swing.JMenuItem ClienteConsultar;
    private javax.swing.JMenuItem ClienteEliminar;
    private javax.swing.JMenuItem ClienteRegistrar;
    private javax.swing.JMenuItem EmpleadoActualizar;
    private javax.swing.JMenuItem EmpleadoConsultar;
    private javax.swing.JMenuItem EmpleadoEliminar;
    private javax.swing.JMenuItem EmpleadoRegistrar;
    private javax.swing.JMenuItem InvantarioActualizar;
    private javax.swing.JMenuItem InvantarioConsultar;
    private javax.swing.JMenu InvantarioReporte;
    private javax.swing.JMenu ModuloAdministracion;
    private javax.swing.JMenu ModuloCliente;
    private javax.swing.JMenu ModuloEmpleado;
    private javax.swing.JMenu ModuloInventario;
    private javax.swing.JMenu ModuloProducto;
    private javax.swing.JMenu ModuloVentas;
    private javax.swing.JMenu ProductoActualizar;
    private javax.swing.JMenuItem ProductoConsultar;
    private javax.swing.JMenuItem ProductoEliminar;
    private javax.swing.JMenu ProductoRegistrar;
    private javax.swing.JMenuItem VentaConsultar;
    private javax.swing.JMenuItem VentaFactura;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
